version: '3.6'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bakayaro
      POSTGRES_DB: agreement_db
    networks:
      - default
    ports:
      - 5432:5432