version: '3.6'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${AGREEMENT_DB_USER}
      POSTGRES_PASSWORD: ${AGREEMENT_DB_PASSWORD}
      POSTGRES_DB: ${AGREEMENT_DB_DB}
    networks:
      - default
    ports:
      - 5432:5432